server:
  port: 9090
  
---

spring: 
     datasource:
        url: jdbc:oracle:thin:@localhost:1521/orclpdb
        username: HR
        password: hetal
        driver-class-name: oracle.jdbc.OracleDriver